### PR TITLE
Include storage class details in cli acorn volumes (#1229)

### LINKED ISSUE #1229: Include storage class details in `acorn volumes`
Server version - `acorn version v0.5.1-65-ge8a480d5+e8a480d5`

Steps to reproduce the problem:
Deploy an app with volumes.
List the volumes using `acorn volumes`

Volume details does not include storage class information.

```
 % acorn volumes       
NAME                                       APP-NAME     BOUND-VOLUME   CAPACITY   STATUS     ACCESS-MODES   CREATED
pvc-e9b4d0fe-3b4e-4753-8fa1-79f37cfae99b   mytestnew1   pgdata1        10G        bound      RWO            13m ago
```

### PR DESCRIPTION
**Pull request by jacobdonenfeld**
### Checklist
- [x] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [x] The title of this PR ends with a link to the main issue being address in paranthesis, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/acorn/pull/1199)
- [x] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keyworkds](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [x] Commits follow [contributing guidance](https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits)
- [x] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [x] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description

Closes #1229

### CODE REVIEW

File: pkg/tables/tables.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ var (
 		{"App-Name", "Status.AppName"},
 		{"Bound-Volume", "Status.VolumeName"},
 		{"Capacity", "Spec.Capacity"},
+		{"Storage-Class", "Spec.Class"},
```
Comment (thedadams) [inline pkg/tables/tables.go:26]: Let's make this Volume-Class since the nomenclature is changing soon.

Comment (jacobdonenfeld) [reply pkg/tables/tables.go]: Updated

**Review by thedadams — APPROVED** [review]
