### PR TITLE
fix info's integration tests breaking on eks (#1244)

### LINKED ISSUE #1244: EKS tests broken due to checking a specific number of namespaces
broken by #1193

### PR DESCRIPTION
**Pull request by jacobdonenfeld**
Refactoring integration tests to use generateName when creating namespaces, as well as verifying namespace names, instead of the length of info's response. This allows it to be more flexible on what cluster it is running on, and allowing other namespaces to preexist.

### Checklist
- [x] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [x] The title of this PR ends with a link to the main issue being address in paranthesis, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/acorn/pull/1199)
- [x] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keyworkds](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [x] Commits follow [contributing guidance](https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits)
- [x] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [x] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description

Closes #1244

### CODE REVIEW

**Review by tylerslaton — APPROVED** [review]

File: integration/helper/assertions.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+		if count, found := set[parsedValue]; !found {
+			return false
+		} else if count < 1 {
+			// Provide a useful failure message
+			assert.Contains(t, set, parsedValue)
+			return false
+		} else {
+			set[parsedValue] = count - 1
+		}
+	}
```
Comment (thedadams) [inline integration/helper/assertions.go:31]: If `parsedValue` is in `set`, but `count < 1`, then I think `assert.Contains` will pass. Also, this can be simplified. Note that reading a key that doesn't exist in a map is perfectly valid and will return the type's zero value.
```suggestion
		if set[parsedValue] < 1 {
			return false
		} 
		set[parsedValue]--
```

File: integration/helper/namespace.go [hunk 2]
```diff
@@ -40,17 +57,19 @@ func NamedTempProject(t *testing.T, client client.Client, name string) *corev1.N
...
 	}
-	return namedTempCreate(t, client, ns)
+	return tempCreateHelper(t, client, ns)
 }
 
-func namedTempCreate(t *testing.T, client client.Client, namespaceObject corev1.Namespace) *corev1.Namespace {
+func tempCreateHelper(t *testing.T, client client.Client, namespaceObject corev1.Namespace) *corev1.Namespace {
 	t.Helper()
-	namespaceName := namespaceObject.GetNamespace()
+	namespaceName := namespaceObject.GetNamespace() // Will be "" for generateName
```
Comment (thedadams) [inline integration/helper/namespace.go:65]: Do you mean `namespaceObject.GetName()` here? I think `namespaceObject.GetNamespace()` is always `""`.

File: integration/helper/namespace.go [hunk 3]
```diff
@@ -73,8 +92,11 @@ func namedTempCreate(t *testing.T, client client.Client, namespaceObject corev1.
 		t.Fatal(err)
 		return nil
 	}
+
 	t.Cleanup(func() {
-		namespaceDeleting := namespaceName
+		// At this point, if using generateName
+		// .getNamespace() and .Namespace aren't populated, just Name
```
Comment (thedadams) [inline integration/helper/namespace.go:98]: I think this comment should be updated as well.

**Review by thedadams — CHANGES_REQUESTED** [review]

File: integration/helper/assertions.go (hunk 1 above)
Comment (jacobdonenfeld) [reply integration/helper/assertions.go]: Great point, moved the assertion outside of the function. TY

**Review by thedadams — APPROVED** [review]
